### ISSUE TITLE
Self referencing host and port ENV

### ISSUE THREAD

**Issue by jmatsushita** [apparatus/fuge-config#8] opened 2017-05-24 08:19 UTC
Hi there,

There used to be autogenerated ENV for the host and port that used the same SERVICE_HOST and SERVICE_PORT name which allowed to reuse code for things like listening. Now they are available with `${SERVICE_NAME}_PORT` which is great for referencing services from one another, but not so great for self referencing.

Would you consider reintroducing this?

Cheers,

Jun

**Comment by pelger** [comment] 2017-06-11 07:44
Absolutely this was an oversight when adding that feature and will be corrected in the next release - my apologies for this!

**Comment by jmatsushita** [comment] 2017-06-11 11:11
That's great thanks a lot for your awesome work!

**Comment by pelger** [comment] 2017-06-11 19:30
Most welcome glad its's of use!

**Comment by pelger** [comment] 2017-06-11 20:05
Just a quick note on this point. The reason for this change is so that the generated environment matches that of a production deployment in Kubernetes. In other words fuge generates an environment that matches the same set of variables that are available once a service is deployed onto a cluster. I believe that this is also the same set for docker swarm. Agreed that Fuge will also generate the self referencing ones for convenience but be aware that you will need to provide these yourself when deploying - assuming you are using Kube or similar.

The self referencing ones will be in the next release - and I'll confirm on this thread once done. Cheers.

**Comment by pelger** [comment] 2017-06-20 06:56
Released and confirmed in 2.0.0 so closing this issue.

**Closed by pelger** 2017-06-20 06:56 UTC
